name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B clean compile
    
    - name: Run tests
      run: mvn test
      env:
        BASE_URL: https://reqres.in
    
    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test-output/
          target/surefire-reports/
    
    - name: Build Docker image
      run: docker build -t automation-framework .
    
    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag automation-framework ${{ secrets.DOCKER_HUB_USERNAME }}/automation-framework:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/automation-framework:latest